### ISSUE TITLE
Link to more info?

### ISSUE THREAD

**Issue by ast** [eflukx/Stepcraft-GRBLizer#1]
Can I purchase this somewhere?

Would be great with a link to more info!

**Comment by eflukx** [comment]
Hi,

Thanks for your interest in this. I do have some (vague) plans to get 50-100 produced of these and sell those online. 

Currently I have (hand)built a few of those, but I have only one Stepcraft 840.. :) Happy to ship one to you @cost price. I also have some bare PCB's left, in case you're interested. Consider yourself a "beta tester": I'm open for improvements for a final version.

Ps. these are "v1" units with some "bugs", mostly swapped pinning of the jacks.

**Comment by ast** [comment]
I have a Stepcraft 420.

I have their motor driver PCB and USB "adapter" but never used it, so it would be great if I could use your GRBLizer with the stepcraft motor driver. It would also tidy things up a bit :-)

I currently use an Arduino with CNC shield R3 (DRV8825 drivers) and GRBL (and some hand wiring to the limit switches).

I'd be happy to betatest this for you.

I'm keeping some notes of my setup here:
http://albinstigo.me/post/stepcraft/

Email me at albin.stigo@gmail.com and lets work something out!

**Comment by eflukx** [comment]
Yep I started off with the standard SC100 USB controller as well (was looking for something that just worked...). But I was _really_ disappointed with the WinPC software delivered with it (I even paid the >200,-- license for it). Also disappointed in the Stepcraft company that they deliver a product aimed for the DIY/hobby/makers market that is based on a fully closed/opaque USB controller. (IMO this harms the value of their product, delivering GRBL or something more open would make very much sense!)

Anyway, give the GRBL firmware a try (nice project!) but needed hardware that nicely fits the Stepcraft.

_Will contact you via email to exchange details._

**Comment by eflukx** [comment]
Oh.. in case someone's interested I have some of the v1 units lying around here..

**Comment by belongumdave** [comment]
Hello there, I will be buying a Stepcraft 2/600 in November, and would like to use Estlcam with this machine. 1/ Do you sell completed PCB? or 2/ if you sell bare PCB? please advise, regards David
