### ISSUE TITLE
Add KiCAD Libraries to Project

### ISSUE THREAD

**Issue by ByteBenderPro** [eflukx/Stepcraft-GRBLizer#3]
Hi There, 
I really like your board and I would like to adapt it to the newer Series 3 Stepcraft machines. 
Unfortunately the KiCAD project you provided uses **libraries** linked to **local paths on your computer**.
Could you provide the used libraries (.lib or similar) to the project and upload them to GitHub? 
I added a screenshot of what the design looks like on a different computer. 
Thank you very much and have a nice day!
Greetings from Germany!
Julius
<img width="1285" alt="Bildschirmfoto 2023-12-02 um 10 21 55" src="https://github.com/eflukx/Stepcraft-GRBLizer/assets/12597949/5f956d55-788d-46bf-85ae-a44b2e148c65">

**Comment by ByteBenderPro** [comment]
The following libraries are mentioned in the KiCAD project (file sym_lib_table):
(sym_lib_table
  (lib (name stepcraft_controller-rescue)(type Legacy)(uri ${KIPRJMOD}/stepcraft_controller-rescue.lib)(options "")(descr ""))
  (lib (name iotta_wsn_rev2)(type Legacy)(uri C:/code/Hardware/iotta-kicad-libs/iotta_wsn_rev2.lib)(options "")(descr ""))
  (lib (name w_connectors)(type Legacy)(uri C:/code/Hardware/iotta-kicad-libs/smisioto.no-ip.org/w_connectors.lib)(options "")(descr ""))
)

**Comment by eflukx** [comment]
Somehow I wasn't notified this issue was open 😨... I'm not sure if this is still relevant to you, sorry about that. Anyway, I will update this project to KiCad 8 and export including all syms shortly!

**Comment by eflukx** [comment]
Updated to Kicad v8, removed all external references (along with some other thing, see commits)
